general.import = ["dracula.toml"]

[bell]
animation = "EaseOutExpo"
duration = 200
color = "#f8f8f2"
command = { program = "/bin/sh", args = ["-c", "afplay /System/Library/Sounds/Glass.aiff & osascript -e 'display notification \"Terminal Bell\" with title \"Alacritty\"'"] }

[font]
size = 11.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"
